# Generated by Django 3.2.15 on 2023-03-10 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='authentication_stage',
            field=models.CharField(default='phone-verified', max_length=20),
        ),
    ]
