# Generated by Django 3.2.15 on 2023-04-06 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogmodel',
            name='author',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
