# Generated by Django 3.2.15 on 2023-04-06 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_blogmodel_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogmodel',
            name='id',
        ),
        migrations.AlterField(
            model_name='blogmodel',
            name='slug',
            field=models.SlugField(max_length=200, primary_key=True, serialize=False, unique=True),
        ),
    ]
