# Generated by Django 4.1.7 on 2023-02-23 16:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("authentication", "0007_alter_customuser_dob"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="dob",
            field=models.DateField(default="2000-01-01"),
        ),
    ]
