# Generated by Django 4.2 on 2023-05-03 14:10

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import shortuuid.django_fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GoldBankModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_id', models.CharField(max_length=10, null=True, unique=True)),
                ('account_number', models.CharField(max_length=18)),
                ('account_name', models.CharField(max_length=50)),
                ('ifsc_code', models.CharField(max_length=11)),
            ],
        ),
        migrations.CreateModel(
            name='GoldInvestorModel',
            fields=[
                ('gold_user_id', shortuuid.django_fields.ShortUUIDField(alphabet=None, length=15, max_length=22, prefix='goldfi_', primary_key=True, serialize=False)),
                ('nomineeName', models.CharField(max_length=100, null=True)),
                ('nomineeDateOfBirth', models.DateField(null=True)),
                ('nomineeRelation', models.CharField(max_length=50)),
                ('user_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GoldRatesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block_id', models.CharField(max_length=10)),
                ('expiry', models.DateTimeField(default=datetime.datetime(2000, 1, 1, 0, 0))),
                ('gold_buy', models.FloatField()),
                ('gold_sell', models.FloatField()),
                ('silver_buy', models.FloatField()),
                ('silver_sell', models.FloatField()),
                ('gold_buy_gst', models.FloatField()),
                ('silver_buy_gst', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='GoldTokenModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expiry', models.DateTimeField(default=datetime.datetime(2000, 1, 1, 0, 0))),
                ('token', models.CharField(max_length=100)),
                ('token_type', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='GoldTransactionModel',
            fields=[
                ('gold_txn_id', shortuuid.django_fields.ShortUUIDField(alphabet=None, length=20, max_length=20, prefix='', primary_key=True, serialize=False)),
                ('txn_type', models.CharField(max_length=4)),
                ('block_id', models.CharField(max_length=10)),
                ('lock_price', models.FloatField()),
                ('metal_type', models.CharField(max_length=6)),
                ('amount', models.FloatField()),
                ('status', models.BooleanField(default=False)),
                ('bank_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gold.goldbankmodel', to_field='bank_id')),
                ('gold_user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gold.goldinvestormodel')),
            ],
        ),
        migrations.AddField(
            model_name='goldbankmodel',
            name='gold_user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gold.goldinvestormodel'),
        ),
        migrations.CreateModel(
            name='GoldAddressModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_id', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=100)),
                ('pincode', models.CharField(max_length=8)),
                ('mobile', models.CharField(max_length=15)),
                ('gold_user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gold.goldinvestormodel')),
            ],
        ),
    ]
