# Generated by Django 4.2 on 2023-05-03 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gold', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goldtokenmodel',
            name='token',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='goldtokenmodel',
            name='token_type',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
