# Generated by Django 4.2 on 2023-05-03 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gold', '0002_alter_goldtokenmodel_token_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goldratesmodel',
            name='block_id',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
