# Generated by Django 4.2 on 2023-05-03 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gold', '0003_alter_goldratesmodel_block_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goldratesmodel',
            name='gold_buy',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='goldratesmodel',
            name='gold_buy_gst',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='goldratesmodel',
            name='gold_sell',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='goldratesmodel',
            name='silver_buy',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='goldratesmodel',
            name='silver_buy_gst',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='goldratesmodel',
            name='silver_sell',
            field=models.FloatField(default=0),
        ),
    ]
