# Generated by Django 4.1.7 on 2023-05-10 13:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gold', '0004_alter_goldratesmodel_gold_buy_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoldAutopayModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('autopay_amount', models.IntegerField()),
                ('startdate', models.DateField()),
                ('processed', models.IntegerField(default=0)),
                ('gold_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gold.goldinvestormodel')),
            ],
        ),
    ]
