# Generated by Django 4.1.7 on 2023-05-25 17:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gold', '0005_goldautopaymodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goldratesmodel',
            name='expiry',
            field=models.DateTimeField(default=datetime.datetime(1999, 12, 31, 18, 30, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='goldtokenmodel',
            name='expiry',
            field=models.DateTimeField(default=datetime.datetime(1999, 12, 31, 18, 30, tzinfo=datetime.timezone.utc)),
        ),
    ]
