# Generated by Django 4.1.7 on 2023-05-27 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gold', '0006_alter_goldratesmodel_expiry_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='goldtransactionmodel',
            name='is_autopay',
            field=models.BooleanField(default=False),
        ),
    ]
