# Generated by Django 4.1.7 on 2023-02-23 16:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("authentication", "0003_alter_customuser_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="id",
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
