# Generated by Django 4.1.7 on 2023-02-23 16:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("authentication", "0006_customuser_is_admin"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="dob",
            field=models.DateField(default="0000-00-00"),
        ),
    ]
